name: Build

on:
  push:
    paths-ignore:
      - README.md
      - .gitignore
      - .github/**

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [18.x]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: npm install, build
        run: |
          npm install
        env:
          CI: true
